apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169273650
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169273650
    app.kubernetes.io/part-of: test-app-169273650
  name: java-quarkus-169273650
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-169273650
status:
  loadBalancer: {}
